### ISSUE TITLE
Minor bugs and suggestions

### ISSUE THREAD

**Issue by ghost** [sixpounder/game-of-life#1]
Hello, finally a nice Game of Life app! 🥰

I found some smaller issues:

1. In Edit mode, right clicking brings up the window menu instead of only killing a cell.
2. If you create a new universe while the current simulation is running, it seems to not do anything.
3. Sometimes when I create a custom blank universe, add some cells manually and then select a new universe from template, the new template universe only blinks through once and then the grid reverts to the previous one. Not entirely sure how that works.

Some suggestions:

1. is the edit mode necessary? Perhaps have it turned on all the time? There doesn't seem to be another reason for clicking the grid other than modifying cells - or rather, you could move the window that way but you could make it in a way that cells are added on mouse release instead of click start and if the window is dragged, cancel adding them on release.

2. maybe make an option for the cell changes being slightly animated (fast opacity 0 - 1 change), might make for a smoother viewing experience.

3. Maybe an option where resizing the window could instead enlarge the playing grid instead of scaling the same number of cells to the available space.

**Comment by sixpounder** [comment]
The first two points are already addressed, it's a bug that came out of a wrong merge I made during the first release process. As for the third I did not notice this behavior but I will double check and fix it if needed.

The edit mode is not necessary but it's there because right now it is only meant to edit a single cell but in future versions I intend to provide "brushes" such as "click to add a glider" and things like that.

**Comment by sixpounder** [comment]
2. That is going to happen in some future release for sure :)
3. This is trickier: without going into too much detail, a universe is a location of memory that gets locked to be sent across thread boundaries. This frees the main thread (which gtk uses for rendering) and makes drawing much faster. Changing the universe size means moving the content of that memory into another, changing its allocated "stuff" and recalculating current cells. This would make the main thread wait significantly longer than a few milliseconds, and considering that a resize is an event that can happen multiple time in a very narrow time frame I am not sure that there is a smart way to implement this. Will give it a tought, but if you have any ideas PR are always open!
