### ISSUE TITLE
Make use of primary mouse button when not in edit mode

### ISSUE THREAD

**Issue by majjejjam** [sixpounder/game-of-life#10]
Right now, using the mouse on the canvas when edit mode is not activated doesn't do anything. Maybe it could

1. pan the canvas or
2. move the window.

For the first point, I realize the canvas is static and tiling. I saw you addressed the issues with changing this in #1. But maybe the second point would make sense and not be too difficult to implement?

Great app, thanks for your work!

**Comment by sixpounder** [comment]
I do not recall if the window handle can be set / unset sensitive to input in gtk, but I guess it can. Will investigate the possibility for upcoming releases.

**Comment by sixpounder** [comment]
Further investigating the issue I realized I was dumb enough not to account for "sensitive" property of a widget - the window handle - to propagate to all child. Hence, if I try to wrap everything in a single gtk::WindowHandle and use sensitive property to determine when it can move or not - in edit mode - it just renders all child widgets insensitive as well.

Not sure if there is a smart way to do this, so I am closing the issue for the moment. Feel free to reopen - or PR :) - if you come up with a solution.
