### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [sixpounder/game-of-life#12]
The current summary "A simulator of Conway's game of life" isn't great (too long, starts with an article, odd casing on "Game of Life").

I'd simplify it to something like "Play Conway's Game of Life".

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by sixpounder** [comment]
Closed by https://github.com/sixpounder/game-of-life/commit/7e219ee2169d21586fdf2c0bc17e690a52f4b019
