### ISSUE TITLE
Issues with unregistered changes while game is running

### ISSUE THREAD

**Issue by LinuxinaBit** [sixpounder/game-of-life#15]
When the game is running, changes don't register at all, including the creation of a new universe.
I suggest automatically stopping when certain things happen, like when the the random button is pressed, the mouse starts drawing, or when any menu window is open.
Auto-resume should happen when things that don't drastically change the field stop the game (ex. drawing should auto resume, the random button should not).

**Comment by sixpounder** [comment]
Closed by https://github.com/sixpounder/game-of-life/commit/8312afc4c45b596412160834bf5414a75dc3d0fc
