### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [sixpounder/game-of-life#5]
The current icon is in line with the guidelines, but a little bit simplistic. Would you be interested in help with a new one?

Here's a quck thing I tried, basically just making the existing icon a little bit more complex/interesting. I'd be happy to try something else though.

![image](https://user-images.githubusercontent.com/1908896/211634169-105c99a7-c05f-485c-a9a3-c5d1559a4f6b.png)

**Comment by sixpounder** [comment]
I would not only be interested but I would be really happy to have a PR for this!

**Comment by bertob** [comment]
Looking at it again, the square is a bit boring. How about something like this?

![image](https://user-images.githubusercontent.com/1908896/211940771-11ef976b-26cb-48e1-873f-7c0c120b0129.png)

**Comment by sixpounder** [comment]
To be honest I can't make up my mind, I like em both :) but I'll try to give my 2 cents anyway, even though I am defenetly not a designer. I guess it boils down to taste and the perception of empty spaces one might have - the second version looks to leave more room on the top part, while the first looks "solid".

The first might use some more margin between the square edges and the outermost cells, while the second doens't need any of that.

The colors of the second version however feel more balanced with their surroundings.

**Comment by bertob** [comment]
Yeah, unique shapes are nice, but the last one is maybe a bit too complex. Here's another attempt trying to combine the two:

![image](https://user-images.githubusercontent.com/1908896/212142682-aeefe651-5090-472b-a465-7f65ec5c3e59.png)
