### ISSUE TITLE
Odd primary menu button shape

### ISSUE THREAD

**Issue by bertob** [sixpounder/game-of-life#6]
The primary menu button is currently an odd oval shape, I'd suggest making it circular like the design mode and random buttons.

![image](https://user-images.githubusercontent.com/1908896/211634548-582bf19d-572a-4c77-887c-73039243119e.png)

**Comment by sixpounder** [comment]
I missed a couple properties in the ui definition. Thank you for pointing this out!

**Comment by sixpounder** [comment]
Closed by https://github.com/sixpounder/game-of-life/commit/0993d254a03b7baed69c33ca29ad90fda60a84b5
