### ISSUE TITLE
Primary menu papercuts

### ISSUE THREAD

**Issue by bertob** [sixpounder/game-of-life#7]
A few papercuts with the primary menu:
- Menu items should use title case capitalization (see https://developer.gnome.org/hig/guidelines/writing-style.html)
- The Quit item is a bit odd, that's usually only for apps that run in the background. I'd recommend having a regular close button in the toolbar, and maybe moving the primary menu to the left for visual balance.
- The About item label should be "About $APPNAME"

![image](https://user-images.githubusercontent.com/1908896/211635249-2f7a5174-0bba-4c0e-aa5e-4f25577ddb9a.png)

**Comment by sixpounder** [comment]
All fair, the only doubt I may have is about the close button - which I assume you would place on the right. Wouldn't it be odd to have a close button placed at the bottom of a window?

I know using a bottom toolbar is odd to begin with. Would you consider this to break HIG guidelines and advise to restore a top toolbar as well?

**Comment by sixpounder** [comment]
Other problems you pointed out resolved by https://github.com/sixpounder/game-of-life/commit/0993d254a03b7baed69c33ca29ad90fda60a84b5. I am leaving this issue open if you want to further discuss my previous question

**Comment by bertob** [comment]
> All fair, the only doubt I may have is about the close button - which I assume you would place on the right. Wouldn't it be odd to have a close button placed at the bottom of a window?

Maybe, but then the window handle is at the bottom too. Worth trying, I think :)

Alternatively moving the whole thing to the top is also an option, though not sure how that would feel layout-wise. I guess a second headerbar at the top with just close and primary menu would also be an option given that space is not that much of a constraint for this app.

**Comment by sixpounder** [comment]
I just pushed un update to flathub with the bottom toolbar / right close button solution. Let's see how it turns out, tell me what you think about it.

**Comment by bertob** [comment]
Ok, I'll check it out. BTW I can also build branches if you want, no need to test this stuff in production :)

**Comment by sixpounder** [comment]
Of course I didn't update the prod branch just to test it :) Once I tried out this version it kinda convinced me - I think - and so I made version 0.3.1.

**Comment by bertob** [comment]
This looks better to me, though I wonder if the original size would look better on the close button. The small X in the large button feels off somehow.

![image](https://user-images.githubusercontent.com/1908896/211936429-fab8be62-fe6c-4b82-8e6f-db513d4ddfa3.png)

**Comment by sixpounder** [comment]
I tried at first, but the smaller button felt "off" being the only different sized one, at least to me.

**Comment by bertob** [comment]
Do you have a screenshot?

**Comment by sixpounder** [comment]
![image](https://user-images.githubusercontent.com/187334/211950951-f7cd17f2-d5f8-4965-b556-4766b033a828.png)

**Comment by bertob** [comment]
That looks better to me, it's more balanced against the non-raised primary menu on the left.

**Comment by sixpounder** [comment]
Commited in https://github.com/sixpounder/game-of-life/commit/ff7fcacb17b56bccc6a23040f56f10c7ddff832b
