### ISSUE TITLE
Change input for cell deletion

### ISSUE THREAD

**Issue by majjejjam** [sixpounder/game-of-life#9]
I think it would feel better if the primary mouse button was used both for adding and deleting cells. Clicking would simply toggle the state of a cell.

**Comment by sixpounder** [comment]
Not really convinced. I actually built it like that in the first commits but that didn't sound right, but that could just be personal taste. I am leaving this open is anyone wants to further explorer the issue anyway.

**Comment by sixpounder** [comment]
The way I see it the main problem is during drag mode: say the primary mouse button toggles the state, which is not a problem when clicking and releasing on a single cell. But using toggle mode while clicking and dragging would cause multiple cell to toggle their state from dead to alive, which is really counterintuitive to me.

A "solution" could be not allowing toggle during drag but use the first toggled state for all subsequently touched cells, but this is a clear UX inconsistency to me - same input, different outcomes.
